### ISSUE TITLE
Dropdown arrow has different scale in Chrome and Firefox

### ISSUE THREAD

**Issue by joglr** [git-visual/git-visual#216]
![image](https://user-images.githubusercontent.com/1959615/156327549-c5de7410-2c22-4bd1-8a6d-2c602e778fb7.png)

**Comment by tjomson** [comment]
In firefox:
![billede](https://user-images.githubusercontent.com/23435481/156327710-8c91ed05-c21c-4965-806e-bb32fe2e2b5f.png)

The arrow also wiggles on hover

**Comment by emiljapelt** [comment]
the css property 'scale', is used for the hover effect. It is only supported in Firefox and Safari.
