### ISSUE TITLE
Make tool runnable

### ISSUE THREAD

**Issue by joglr** [git-visual/git-visual#228]
In parallel,
1. Begin parsing
2. Begin building front-end

When parsing done,
Check if front-end is ready.
If front-end not ready, 

1. Build static front-end
2. Build back-end static front-end

Developer experience

End user experience
 - Pre built parser and front-end.
 - Running command starts parser and serves front-end.

- [ ] Resolves #229
- [ ] Resolves #154 
- [ ]

**Comment by mircealungu** [comment]
Folks, I was just thinking a bit more about this. 
Remember that I've said that we're targeting developers. 

Thus, the only thing that I think is required for having an MVP is 
- not having any hardcoded paths anymore 
- not crashing on "unknown authors"
- taking a parameter for the folder that needs to be analyzed

It does not matter if I need to run one or two commands separately or anything that a developer can do is fine. 

I'm saying this just so you don't spend too much time on this. After all, our focus should be on discovering the most insightful visual representations of software evolution ;)

**Comment by joglr** [comment]
> Folks, I was just thinking a bit more about this. Remember that I've said that we're targeting developers.
> 
> Thus, the only thing that I think is required for having an MVP is
> 
> * not having any hardcoded paths anymore
> * not crashing on "unknown authors"
> * taking a parameter for the folder that needs to be analyzed
> 
> It does not matter if I need to run one or two commands separately or pass CLI arguments, etc. Anything that a developer can do is fine.
> 
> I'm saying this just so you don't spend too much time on this. After all, our focus should be on discovering the most insightful visual representations of software evolution ;)

I agree. We only spent 5 minutes on adding a script that runs all the proper commands, but we agreed that we shouldn't make any fancy CLI orchestration.
