### ISSUE TITLE
Decouple interfaces between front-end and parser in terms of models

### ISSUE THREAD

**Issue by joglr** [git-visual/git-visual#42]
The front-end necessarily won't need the same data as the parser outputs. Therefore, we propose having two separate data models and a converter in between, to reduce coupling.

- [ ] Determine what information the parser provides
- [ ] Determine front-end data model needed
- [ ] Write a converter from parser data model to front-end data model

**Comment by mircealungu** [comment]
I'd argue this is secondary - let's focus on generating a useful vis and testing it with users and leaving the interface standardizations for later maybe?

**Comment by joglr** [comment]
This has been partially addressed by having hydrated and non-hydrated interfaces 
https://github.com/git-visual/git-visual/blob/eb02370d36b21ca7f03851bb57262e4952f46d09/parser/src/model.ts
